export { default as Home } from './Home'
export { default as Skills } from './Skills'
export { default as Experience } from './Experience'
export { default as Projects } from './Projects'
export { default as Contact } from './Contact'
